spring:
  application:
    name: profiles

  devtools:
    restart:
      enabled: true

  profiles:
    active: dev

logging:
  level:
    org.springframework: debug

currency-service:
  url: https://default.currency.ie
  username: default-currency
  key: default-currency$
